services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperfolio_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - hyperfolio_net

  mysql:
    image: mysql:8.0
    container_name: hyperfolio_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperfolio
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    networks:
      - hyperfolio_net
networks:
  hyperfolio_net:
    driver: bridge